language: lisp

env: PREFIX="$(pwd)/sbcl"
     SBCL_HOME="$(pwd)/sbcl/lib/sbcl"
     SBCL="$(pwd)/sbcl/bin/sbcl"
     SBCL_OPTIONS="--noinform --no-userinit"

install:
  - curl -L "${SBCL_DOWNLOAD_URL}" | tar -xj
  - ( cd sbcl-* && INSTALL_ROOT="${PREFIX}" sh install.sh )

  - curl -o cl "${CL_LAUNCH_DOWNLOAD_URL}"
  - chmod +x cl

  - curl -o quicklisp.lisp "${QUICKLISP_DOWNLOAD_URL}"
  - ./cl -L quicklisp.lisp '(quicklisp-quickstart:install)'

script:
  - ./cl
      -S '(:source-registry (:directory "'$(pwd)'") :ignore-inherited-configuration)'
      -Q
      -s architecture.builder-protocol/test
      -s architecture.builder-protocol.xpath/test
      -s architecture.builder-protocol.json/test
      -s architecture.builder-protocol.universal-builder/test
      -s :architecture.builder-protocol.print-tree/test
      '(or (and (architecture.builder-protocol.test:run-tests)
                (architecture.builder-protocol.xpath.test:run-tests)
                (architecture.builder-protocol.json.test:run-tests)
                (architecture.builder-protocol.universal-builder.test:run-tests)
                (architecture.builder-protocol.print-tree.test:run-tests))
           (uiop:quit -1))'
